### ISSUE TITLE
Error asserting in MacOS CoreGraphics

### ISSUE THREAD

**Issue by niktolis** [cpp-io2d/P0267_RefImpl#154]
https://github.com/niktolis/P0267_RefImpl/blob/71f93deb4a987099068f909fb9ffa7bb83b458d6/P0267_RefImpl/P0267_RefImpl/coregraphics/xio2d_cg_display.cpp#L8

Seems like there is an issue with GraphicsContext created by NSApplication which might be related to the latest MacOS SDK releases

**Comment by nellsummer** [comment]
Did you fix the issue?

I ran into this error in the same line in your link when running my executable: 
```
display buffer and back buffer have different pixel layouts: 0(display buffer) and 8194(back buffer).
Assertion failed: (back_buffer_size.width >= 1. && back_buffer_size.height >= 1. && display_buffer_size.width >= 1. && display_buffer_size.height >= 1.), function _ScaledBackBufferRect, file xio2d_cg_display.cpp, line 9.
```
