### ISSUE TITLE
`std` namespace ensures UB

### ISSUE THREAD

**Issue by johnmcfarlane** [cpp-io2d/P0267_RefImpl#88]
I'm suspect this library cannot be used in a correct, ISO C++-confirming program. http://eel.is/c++draft/namespace.std#1
It *shouldn't* be necessary to use `std` to illustrate P0267. You might get away with wrapping std in another namespace but I'm not certain.

**Comment by johnmcfarlane** [comment]
Until then, wouldn't you like people to try it out? I can't see anything in the README to inform users that they should not attempt to compile this library.

**Comment by hatcat** [comment]
Does this solve it? https://github.com/cpp-io2d/P0267_RefImpl/pull/89

**Comment by johnmcfarlane** [comment]
Yup, that's much better, thanks. I still might want to try out io2d in a bug-free (ha!) project. In which case, hopefully there are other implementations out there.
