### ISSUE TITLE
narrow io2d library targets to ONE

### ISSUE THREAD

**Issue by DavidLudwig** [cpp-io2d/P0267_RefImpl#97]
TODO: narrow the amount of non-sample, non-test, "io2d" targets in the reference implementation down to one.

Right now, there are several library targets, such as:
* io2d_core
* io2d_cairo
* io2d_cairo_xlib
* io2d_cairo_win32
* ... and so on ...

Is this necessary?  It seems a bit confusing to me.

**Comment by Lyberta** [comment]
I was under impression that this was initially done to support several backends and the user could choose a backend.

**Comment by DavidLudwig** [comment]
I think that multiple backends could be supported with one .lib/.a/.so.  Other graphically-oriented libraries do this fairly often.

Do you (or anyone else reading this!) see good reason not to merge these targets into one, "io2d" target?

**Comment by DavidLudwig** [comment]
To add to my comments above: the feature I am primarily looking for here is to enable an io2d user/developer to link to the io2d reference implementation without first requiring that they specify an individual backend.  If they want to customize it later on, I hope that there ends up being a way to do it.  I'd rather not, though, mandate that they make this choice.

**Comment by Lyberta** [comment]
In #83 I made sure that the users won't need to deal with specific backends. Several targets are simply implementation detail for 99% of users.

**Comment by DavidLudwig** [comment]
I am closing this as I can see reasons to have per-platform targets, and I think my initial thought (and title, perhaps) may have been wrong.

I would, though, like to see a minimum number of library names when linking to the ref-impl.  I wonder how easily this could be done in CMake (for which I am a relative newcomer, and am trying to study up on).

**Comment by DavidLudwig** [comment]
@Lyberta, thanks for putting #83 together!
